### ISSUE TITLE
[BUG] Unable to deploy new versions of website

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/glasswall-sre.github.io#44]
Under the CI/CD pipeline, you can see that we are currently unable to deploy any updates to the website.

When running locally
`yarn start`
I get the following output
```
yarn run v1.22.10
$ docusaurus start
Starting the development server...
TypeError: Cannot read property 'links' of undefined
    at getFooterTranslationFile (/Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/theme-classic/lib/translations.js:63:54)
    at getTranslationFiles (/Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/theme-classic/lib/translations.js:116:14)
    at Object.getTranslationFiles (/Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/theme-classic/lib/index.js:114:76)
    at /Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/core/lib/server/plugins/index.js:60:189
    at Array.map (<anonymous>)
    at Object.loadPlugins (/Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/core/lib/server/plugins/index.js:58:83)
    at async Object.load (/Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/core/lib/server/index.js:108:82)
    at async start (/Users/ashpowell/Git/glasswall-sre.github.io/node_modules/@docusaurus/core/lib/commands/start.js:43:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AshKapow** [comment]
https://github.com/glasswall-sre/glasswall-sre.github.io/commit/6e6f0fcbec46d532f68a54d282ae7276de0a8507
